name: PHPUnit Tests

on:
  push:
    branches: [ "m4Submission" ]
  pull_request:
    branches: [ "m4Submission" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tickethub
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Database Backup
        run: |
          mysql -u root -proot -h 127.0.0.1 -P 3306 tickethub < m4Submission/tickethubNew.sql

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      # Other steps for setup, copying .env, installing dependencies, etc.

      - name: Execute PHPUnit Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: tickethub
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php vendor/bin/phpunit --configuration phpunit.xml
